# minimal training/model hyperparams
# check for sanity (overrided by ingest.yaml)
data_root: ${oc.env:DATA_SHARDS_ROOT,./data/shards}
shards_pattern: "data/shards/laion_aesthetic_6p5/{000000..000009}.tar"
shuffle_buffer: 2000
num_workers: 4
batch_size: 8
image_size: 256
center_crop: false